### ISSUE TITLE
typeof undefined when `-std=` specified

### ISSUE THREAD

**Issue by dm9pZCAq** [nbulischeck/list.h#6]
how to reproduce:
compile [Basic Working Example](https://github.com/nbulischeck/list.h#basic-working-example) with any `-std`
```sh
cc -std=c11 test.c
```

and it produce:
```
list.h:11:17: warning: implicit declaration of function 'typeof' [-Wimplicit-function-declaration]
   11 |                 typeof(head) _tmp = head; \
      |                 ^~~~~~
```
and more

---

with `-Dtypeof=__typeof__` everything compiles fine

so i suggest change all `typeof()` to `__typeof__()`

https://stackoverflow.com/a/27508311

**Comment by nbulischeck** [comment]
Resolved in c17f195fa2253583e3a32d88bc6094addc4e1be1
